export const METADATA = {
  CONTROLLER: Symbol('CONTROLLER'),
  CONTROLLER_METHOD: Symbol('CONTROLLER_METHOD'),
  CONTROLLER_PARAMETER: Symbol('CONTROLLER_PARAMETER'),
  CONTROLLER_PARAMETER_VALID: Symbol('CONTROLLER_PARAMETER_VALID'),
  MIDDLEWARE: Symbol('MIDDLEWARE'),
  SERVICE: Symbol('SERVICE'),
  CONFIG: Symbol('CONFIG'),
  LOGGER: Symbol('FRAMEWORK_LOGGER')
}

export const COMPONENT = {
  CONFIG: Symbol('CONFIG'),
  MODULE: Symbol('MODULE'),
  ASPECT: Symbol('ASPECT'),
  SERVICE: Symbol('SERVICE'),
  MIDDLEWARE: Symbol('MIDDLEWARE'),
  CONTROLLER: Symbol('CONTROLLER'),
  APPLICATION: Symbol('APPLICATION')
}

export const CLUSTER = {
  REGISTERD_FUNCTIONS: Symbol('REGISTERD_FUNCTIONS')
}
